apiVersion: v1
kind: Service
metadata:
  name: netflix-clone-service
  labels:
    app: netflix-clone
spec:
  type: ClusterIP
  selector:
    app: netflix-clone
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP